#!/usr/bin/env python3

import os
import requests
import webbrowser

from functools import lru_cache

import pandas as pd
from tabulate import tabulate


@lru_cache
def current_thunderbird_versions():
    url = "https://product-details.mozilla.org/1.0/thunderbird_versions.json"
    response = requests.get(url)
    data = response.json()
    return data


@lru_cache
def thunderbird_daily_version():
    thunderbird_versions = current_thunderbird_versions()
    daily = thunderbird_versions["LATEST_THUNDERBIRD_NIGHTLY_VERSION"].split(".")[0]
    return daily


@lru_cache
def thunderbird_beta_version():
    thunderbird_versions = current_thunderbird_versions()
    beta = thunderbird_versions["LATEST_THUNDERBIRD_DEVEL_VERSION"].split(".")[0]
    return beta


@lru_cache
def thunderbird_release_version():
    thunderbird_versions = current_thunderbird_versions()
    release = thunderbird_versions["LATEST_THUNDERBIRD_VERSION"].split(".")[0]
    return release


@lru_cache
def thunderbird_esr_version():
    thunderbird_versions = current_thunderbird_versions()
    esr = thunderbird_versions["THUNDERBIRD_ESR"].split(".")[0]
    return esr

@lru_cache
def thunderbird_esr_next_version():
    thunderbird_versions = current_thunderbird_versions()
    esr = thunderbird_versions["THUNDERBIRD_ESR_NEXT"].split(".")[0]
    return esr


def beta_potential_uplifts(fixed_in, affects, regression=True):
    if regression:
        regression = "keywords=regression&keywords_type=allwords&"
    else:
        regression = "keywords=regression&keywords_type=nowords&"
    url = (
        "https://bugzilla.mozilla.org/buglist.cgi?chfield=resolution&"
        "chfieldfrom=2023-12-01&"
        "chfieldvalue=fixed&"
        "classification=Client%20Software&"
        "classification=Components&"
        f"{regression}"
        "f1=short_desc&"
        "f2=component&"
        "f3=OP&"
        "f4=target_milestone&"
        f"f5=cf_status_thunderbird_{affects}&"
        "f6=flagtypes.name&"
        "f7=longdesc&"
        "f8=CP&"
        "n6=1&"
        "n7=1&"
        "o1=nowordssubstr&"
        "o2=nowordssubstr&"
        "o4=substring&"
        "o5=equals&"
        "o6=equals&"
        "o7=substring&"
        "product=Calendar&"
        "product=MailNews%20Core&"
        "product=Thunderbird&"
        "resolution=FIXED&"
        "v1=intermit&"
        "v2=upstream%20build%20test%20theme%20add-on&"
        f"v4={fixed_in}&"
        "v5=affected&"
        "v6=approval-comm-beta%3F&"
        "v7=approved%20for%20beta&"
        "order=bug_id"
    )
    return url


def release_potential_uplifts(fixed_in, affects, regression=True):
    if regression:
        regression = "keywords=regression&keywords_type=allwords&"
    else:
        regression = "keywords=regression&keywords_type=nowords&"
    url = (
        "https://bugzilla.mozilla.org/buglist.cgi?chfield=resolution&"
        "chfieldfrom=2023-12-01&"
        "chfieldvalue=fixed&"
        "classification=Client%20Software&"
        "classification=Components&"
        f"{regression}"
        "f1=short_desc&"
        "f2=component&"
        "f3=OP&"
        "f4=target_milestone&"
        f"f5=cf_status_thunderbird_{affects}&"
        "f6=flagtypes.name&"
        "f7=longdesc&"
        "f8=CP&"
        "n6=1&"
        "n7=1&"
        "o1=nowordssubstr&"
        "o2=nowordssubstr&"
        "o4=substring&"
        "o5=equals&"
        "o6=equals&"
        "o7=substring&"
        "product=Calendar&"
        "product=MailNews%20Core&"
        "product=Thunderbird&"
        "resolution=FIXED&"
        "v1=intermit&"
        "v2=upstream%20build%20test%20theme%20add-on&"
        f"v4={fixed_in}&"
        "v5=affected&"
        "v6=approval-comm-release%3F&"
        "v7=approved%20for%20release&"
        "order=bug_id"
    )
    return url


def _esr_potential_uplifts(esr, target_milestone, regression=True):
    if regression:
        regression = "keywords=regression&keywords_type=allwords&"
    else:
        regression = "keywords=regression&keywords_type=nowords&"
    url = (
        "https://bugzilla.mozilla.org/buglist.cgi?chfield=resolution&"
        "chfieldfrom=2024-05-01&"
        "chfieldvalue=fixed&"
        "classification=Client%20Software&"
        "classification=Components&"
        f"{regression}"
        "f1=short_desc&"
        "f2=component&"
        "f3=OP&"
        f"f4=cf_status_thunderbird_esr{esr}&"
        "f5=longdesc&"
        "f6=target_milestone&"
        "f7=flagtypes.name&"
        f"f8=cf_status_thunderbird_{esr}&"
        "f9=CP&"
        "n5=1&"
        "n7=1&"
        "o1=nowordssubstr&"
        "o2=nowordssubstr&"
        "o4=nowordssubstr&"
        "o5=substring&"
        "o6=anywordssubstr&"
        "o7=equals&"
        "o8=nowordssubstr&"
        "product=Calendar&"
        "product=Chat%20Core&"
        "product=MailNews%20Core&"
        "product=Thunderbird&"
        "resolution=FIXED&"
        "v1=exchange%20ews%20card&"
        "v2=upstream&"
        "v4=fixed%20wontfix%20verified%20unaffected&"
        f"v5=approved%20for%20esr{esr}&"
        f"v6={target_milestone}&"
        f"v7=approval-comm-esr{esr}%3F&"
        "v8=fixed%20wontfix%20verified%20unaffected&"
        "order=component"
    )
    return url


def esr_potential_uplifts(target_milestone, regression=True):
    esr = thunderbird_esr_version()
    return _esr_potential_uplifts(esr, target_milestone, regression)


def esr_next_potential_uplifts(target_milestone, regression=True):
    esr_next = thunderbird_esr_next_version()
    return _esr_potential_uplifts(esr_next, target_milestone, regression)


def approved_but_not_yet_uplifted(channel):
    daily = thunderbird_daily_version()
    beta = thunderbird_beta_version()
    esr = thunderbird_esr_version()
    esr_next = thunderbird_esr_next_version()
    if channel == "beta":
        url = (
            "https://bugzilla.mozilla.org/buglist.cgi?"
            "classification=Client%20Software&"
            "classification=Developer%20Infrastructure&"
            "classification=Components&"
            "classification=Server%20Software&"
            "classification=Other&"
            f"columnlist=bug_type%2Cshort_desc%2Cproduct%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cchangeddate%2Creporter%2Copendate%2Cbug_severity%2Cstatus_whiteboard%2Cversion%2Ckeywords%2Ctarget_milestone%2Ccf_status_thunderbird_{daily}%2Ccf_status_thunderbird_{beta}&"
            "query_format=advanced&"
            "resolution=---&"
            "resolution=FIXED&"
            "f1=OP&"
            "f2=longdesc&"
            "f3=flagtypes.name&"
            "f4=target_milestone&"
            f"f5=cf_status_thunderbird_{beta}&"
            "f6=CP&"
            "f7=OP&"
            "f8=longdesc&"
            "f9=flagtypes.name&"
            "f10=target_milestone&"
            f"f11=cf_status_thunderbird_{beta}&"
            "f12=keywords&"
            "f13=CP&"
            "j_top=OR&"
            "o2=substring&"
            "o3=equals&"
            "o4=substring&"
            "o5=nowordssubstr&"
            "o8=substring&"
            "o9=equals&"
            "o10=substring&"
            "o11=anywordssubstr&"
            "o12=substring&"
            "v2=approved%20for%20beta&"
            "v3=approval-comm-beta%2B&"
            f"v4={daily}&"
            "v5=fixed%20verified&"
            "v8=approved%20for%20beta&"
            "v9=approval-comm-beta%2B&"
            f"v10={daily}&"
            "v11=fixed%20verified&"
            "v12=leave-open"
        )
    elif channel == "release":
        url = (
            "https://bugzilla.mozilla.org/buglist.cgi?"
            "classification=Client%20Software&"
            "classification=Developer%20Infrastructure&"
            "classification=Components&"
            "classification=Server%20Software&"
            "classification=Other&"
            f"columnlist=bug_type%2Cshort_desc%2Cproduct%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cchangeddate%2Creporter%2Copendate%2Cbug_severity%2Cstatus_whiteboard%2Cversion%2Ckeywords%2Ctarget_milestone%2Ccf_status_thunderbird_{beta}%2Ccf_status_thunderbird_{int(beta)-1}&"
            "query_format=advanced&"
            "query_based_on=&"
            "resolution=---&"
            "resolution=FIXED&"
            "f1=OP&"
            "f2=longdesc&"
            "f3=flagtypes.name&"
            f"f4=cf_status_thunderbird_{beta}&"
            f"f5=cf_status_thunderbird_{int(beta)-1}&"
            "f6=CP&"
            "f7=OP&"
            "f8=longdesc&"
            "f9=flagtypes.name&"
            f"f10=cf_status_thunderbird_{beta}&"
            f"f11=cf_status_thunderbird_{int(beta)-1}&"
            "f12=keywords&"
            "f13=CP&"
            "j_top=OR&"
            "o2=substring&"
            "o3=equals&"
            "o4=anywordssubstr&"
            "o5=nowordssubstr&"
            "o8=substring&"
            "o9=equals&"
            "o10=anywordssubstr&"
            "o11=anywordssubstr&"
            "o12=substring&"
            "v2=approved%20for%20release&"
            "v3=approval-comm-release%2B&"
            "v4=fixed%20verified&"
            "v5=fixed%20verified&"
            "v8=approved%20for%20release&"
            "v9=approval-comm-release%2B&"
            "v10=fixed%20verified&"
            "v11=fixed%20verified&"
            "v12=leave-open"
        )
    elif channel == "esr":
        url = (
            "https://bugzilla.mozilla.org/buglist.cgi?"
            "classification=Client%20Software&"
            "classification=Developer%20Infrastructure&"
            "classification=Components&"
            "classification=Server%20Software&"
            "classification=Other&"
            f"columnlist=bug_type%2Cshort_desc%2Cproduct%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cchangeddate%2Creporter%2Copendate%2Cbug_severity%2Cstatus_whiteboard%2Cversion%2Ckeywords%2Ctarget_milestone%2Ccf_status_thunderbird_{beta}%2Ccf_status_thunderbird_{esr}&"
            "query_format=advanced&"
            "query_based_on=&"
            "resolution=---&"
            "resolution=FIXED&"
            "f1=OP&"
            "f2=longdesc&"
            "f3=flagtypes.name&"
            f"f4=cf_status_thunderbird_esr{esr}&"
            "f5=CP&"
            "f6=OP&"
            "f7=longdesc&"
            "f8=flagtypes.name&"
            f"f9=cf_status_thunderbird_esr{esr}&"
            "f10=keywords&"
            "f11=CP&"
            "j_top=OR&"
            "o2=substring&"
            "o3=equals&"
            "o4=nowordssubstr&"
            "o7=substring&"
            "o8=equals&"
            "o9=anywordssubstr&"
            "o10=substring&"
            f"v2=approved%20for%20esr{esr}&"
            f"v3=approval-comm-esr{esr}%2B&"
            "v4=fixed%20verified&"
            f"v7=approved%20for%20esr{esr}&"
            f"v8=approval-comm-esr{esr}%2B&"
            "v9=fixed%20verified&"
            "v10=leave-open"
        )
    elif channel == "esr_next":
        url = (
            "https://bugzilla.mozilla.org/buglist.cgi?"
            "classification=Client%20Software&"
            "classification=Developer%20Infrastructure&"
            "classification=Components&"
            "classification=Server%20Software&"
            "classification=Other&"
            f"columnlist=bug_type%2Cshort_desc%2Cproduct%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cchangeddate%2Creporter%2Copendate%2Cbug_severity%2Cstatus_whiteboard%2Cversion%2Ckeywords%2Ctarget_milestone%2Ccf_status_thunderbird_{beta}%2Ccf_status_thunderbird_{esr_next}&"
            "query_format=advanced&"
            "query_based_on=&"
            "resolution=---&"
            "resolution=FIXED&"
            "f1=OP&"
            "f2=longdesc&"
            "f3=flagtypes.name&"
            f"f4=cf_status_thunderbird_esr{esr_next}&"
            "f5=CP&"
            "f6=OP&"
            "f7=longdesc&"
            "f8=flagtypes.name&"
            f"f9=cf_status_thunderbird_esr{esr_next}&"
            "f10=keywords&"
            "f11=CP&"
            "j_top=OR&"
            "o2=substring&"
            "o3=equals&"
            "o4=nowordssubstr&"
            "o7=substring&"
            "o8=equals&"
            "o9=anywordssubstr&"
            "o10=substring&"
            f"v2=approved%20for%20esr{esr_next}&"
            f"v3=approval-comm-esr{esr_next}%2B&"
            "v4=fixed%20verified&"
            f"v7=approved%20for%20esr{esr_next}&"
            f"v8=approval-comm-esr{esr_next}%2B&"
            "v9=fixed%20verified&"
            "v10=leave-open"
        )

    return url


def print_versions():
    daily_version = thunderbird_daily_version()
    beta_version = thunderbird_beta_version()
    release_version = thunderbird_release_version()
    esr_version = thunderbird_esr_version()
    esr_next_version = thunderbird_esr_next_version()
    table_data = {
        "Category": [
            "daily version",
            "beta version",
            "release version",
            "esr version",
        ],
        "Variable": [
            daily_version,
            beta_version,
            release_version,
            esr_version,
        ],
    }
    if esr_next_version:
        table_data["Category"].append("esr version")
        table_data["Variable"].append(esr_next_version)
    df = pd.DataFrame(table_data)
    table_data = df.values.tolist()
    print(tabulate(table_data, tablefmt="plain", colalign=("left", "left")))


def render_links_to_html(output_file, links):
    html_content = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Release bugzilla queries</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            ul { list-style-type: none; }
            a { text-decoration: none; color: blue; }
            a:hover { text-decoration: underline; }
        </style>
    </head>
    <body>
        <h1>Release bugzilla queries</h1>
        <ul>
    """

    for description, url in links:
        html_content += (
            f'            <li><a href="{url}" target="_blank">{description}</a></li>\n'
        )

    html_content += """
        </ul>
    </body>
    </html>
    """

    with open(output_file, "w") as file:
        file.write(html_content)

    print(f"HTML file generated at {output_file}")
    webbrowser.open(f"file://{output_file}")


def main():
    links = list()
    daily = thunderbird_daily_version()
    beta = thunderbird_beta_version()
    release = thunderbird_release_version()
    esr = thunderbird_esr_version()
    esr_next = thunderbird_esr_next_version()

    print_versions()

    for version in reversed(range(int(daily) - 3, int(daily))):
        links.append(
            (
                f"fixed in {daily}, affects {version} (regression)",
                beta_potential_uplifts(fixed_in=daily, affects=version, regression=True),
            )
        )
        links.append(
            (
                f"fixed in {daily}, affects {version} (non-regression)",
                beta_potential_uplifts(fixed_in=daily, affects=version, regression=False),
            )
        )
    for version in reversed(range(int(beta) - 3, int(beta))):
        links.append(
            (
                f"fixed in {beta}, affects {version} (regression)",
                release_potential_uplifts(fixed_in=beta, affects=version, regression=True),
            )
        )
        links.append(
            (
                f"fixed in {beta}, affects {version} (non-regression)",
                release_potential_uplifts(fixed_in=beta, affects=version, regression=False),
            )
        )
    for version in reversed(range(int(esr) + 1, int(daily) + 1)):
        links.append(
            (
                f"fixed in {version}, may affect {esr}esr (regression)",
                esr_potential_uplifts(target_milestone=version, regression=True),
            )
        )
        links.append(
            (
                f"fixed in {version}, may affect {esr}esr (non-regression)",
                esr_potential_uplifts(target_milestone=version, regression=False),
            )
        )
    if esr_next:
        for version in reversed(range(int(esr_next) + 1, int(daily) + 1)):
            links.append(
                (
                    f"fixed in {version}, may affect {esr_next}esr (regression)",
                    esr_next_potential_uplifts(target_milestone=version, regression=True),
                )
            )
            links.append(
                (
                    f"fixed in {version}, may affect {esr_next}esr (non-regression)",
                    esr_next_potential_uplifts(target_milestone=version, regression=False),
                )
            )
    links.append(
        (
            f"Approved but not yet uplifted to beta {beta}",
            approved_but_not_yet_uplifted("beta"),
        )
    )
    links.append(
        (
            f"Approved but not yet uplifted to release {release}",
            approved_but_not_yet_uplifted("release"),
        )
    )
    links.append(
        (
            f"Approved but not yet uplifted to esr {esr}",
            approved_but_not_yet_uplifted("esr"),
        )
    )
    if esr_next:
        links.append(
            (
                f"Approved but not yet uplifted to esr {esr_next}",
                approved_but_not_yet_uplifted("esr_next"),
            )
        )

    render_links_to_html(
        os.path.join(os.getcwd(), "thunderbird_uplift_queries.html"), links
    )


if __name__ == "__main__":
    main()
